SELECT COUNT(*) FROM MEMBER
;


SELECT MEMBER_NICK FROM MEMBER
WHERE MEMBER_EMAIL = 'user01@kh.or.kr'
AND SECESSION_FL = 'N';

SELECT '안녕하세요' FROM DUAL;



SELECT * FROM MEMBER
WHERE 1 = 0;

-- MEMBER테이블을 복제해서 MEMBER_S 테이블 생성

-- 테이블 컬럼 복제(NOT NULL 제약조건만 복제됨)
CREATE TABLE MEMBER_S
AS SELECT * FROM MEMBER
WHERE 1 = 0;

-- 컬럼 기본값 지정
ALTER TABLE MEMBER_S
MODIFY ENROLL_DT DEFAULT SYSDATE;

ALTER TABLE MEMBER_S
MODIFY SECESSION_FL DEFAULT 'N';

-- PK 제약조건 추가
ALTER TABLE MEMBER_S
ADD CONSTRAINT MEMBER_S_PK PRIMARY KEY(MEMBER_NO);


-- CHECK 제약조건 추가
ALTER TABLE MEMBER_S
ADD CONSTRAINT MEMBER_S_CHK CHECK(SECESSION_FL IN ('Y', 'N') );


-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO_S NOCACHE;
    

-- 샘플데이터 추가
INSERT INTO MEMBER_S VALUES(
    SEQ_MEMBER_NO_S.NEXTVAL,
    'test01@naver.com',
    'pass01!',
    '테스트1',
    '01012341234',
    DEFAULT, DEFAULT, DEFAULT, DEFAULT
);

COMMIT;


-- 아이디, 비밀번호가 일치하는 회원의 전화번호 조회
-- 단, 정상 회원만
SELECT MEMBER_TEL FROM MEMBER_S
WHERE MEMBER_EMAIL = 'test01@naver.com'
AND MEMBER_PW = 'pass01!'
AND SECESSION_FL = 'N';

-- 로그인
SELECT MEMBER_NO,MEMBER_EMAIL,MEMBER_NICK ,MEMBER_TEL,
    MEMBER_ADDR, PROFILE_IMG, 
    TO_CHAR( ENROLL_DT, 'YYYY-MM-DD HH24:MI:SS') AS ENROLL_DT
FROM MEMBER
WHERE MEMBER_EMAIL = ?
AND MEMBER_PW = ?
AND SECESSION_FL = 'N';


-- MEMBER_S 테이블에서 회원번호가 1번인 회원의 비밀번호를 암호화된 비밀번호로 수정
UPDATE MEMBER_S SET
MEMBER_PW = '$2a$10$k3fw.1HaU12LIwydGiufjeFD3mbD8BzhU4B7X4fvwqHEAF19RwJ/C'
WHERE MEMBER_NO = 1;


-- 이메일 중복 검사 (1 중복, 0 사용 가능)
SELECT COUNT(*) FROM MEMBER_S
WHERE MEMBER_EMAIL = 'test01@naver.com'
AND SECESSION_FL = 'N';